{% set name = "cppbktree" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/cppbktree-{{ version }}.tar.gz
  sha256: c0585007737df6978269e266ebdfd8d27eef5db02a69d158115b9662437a3249

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cppbktree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mxmlnkn/cppbktree
  summary: C++ Implementation of a Burkhard-Keller Tree (BK-Tree)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
